import type { FoodEntry } from "@/types/food";

const img = (id: string, w = 900, h = 1200) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&h=${h}&q=82`;

export const seedEntries: FoodEntry[] = [
  {
    id: "olive-oil-squid",
    title: "Olive Oil Squid",
    type: "home",
    rating: 5,
    mood: "fresh",
    atmosphere: { x: 72, y: 30 },
    weather: "21°C · Clear · Evening",
    placeLabel: "At home · Angel",
    effort: "easy",
    notes: "Simple, quick, and bright. More lemon next time.",
    recipe: "Warm olive oil with garlic and chilli. Add squid for a very short cook, then finish with parsley, lemon zest, and toasted bread.",
    timeMinutes: 18,
    city: "London",
    country: "United Kingdom",
    entryDate: "2026-06-14",
    tags: ["Seafood", "Quick", "Summer", "Home", "Favorites"],
    photos: [
      {
        id: "olive-oil-squid-1",
        imageUrl: img("photo-1559847844-5315695dadae", 1000, 1300),
        alt: "Olive oil squid with herbs on a plate"
      }
    ]
  },
  {
    id: "beef-noodle-soup",
    title: "Beef Noodle Soup",
    type: "home",
    rating: 5,
    notes: "Deep broth, soft tendon, a tiny mountain of greens.",
    recipe: "Braise beef shank with soy, tomato, ginger, star anise, and doubanjiang. Serve with wheat noodles and bok choy.",
    timeMinutes: 180,
    city: "London",
    country: "United Kingdom",
    entryDate: "2026-06-10",
    tags: ["Taiwanese", "Comfort", "Rich", "Winter", "Home", "Favorites"],
    photos: [{ id: "beef-noodle-1", imageUrl: img("photo-1569718212165-3a8278d5f624"), alt: "A bowl of beef noodle soup" }]
  },
  {
    id: "cepelinai",
    title: "Cepelinai",
    type: "restaurant",
    rating: 4,
    notes: "Heavy in the best possible way. Sour cream saved the day.",
    wantToRecreate: true,
    restaurantName: "Senoji Trobele",
    city: "Vilnius",
    country: "Lithuania",
    entryDate: "2026-06-03",
    tags: ["Lithuanian", "Restaurant", "Comfort", "Travel", "Rich"],
    photos: [{ id: "cepelinai-1", imageUrl: img("photo-1600628421055-4d30de868b8f"), alt: "Potato dumplings with cream" }]
  },
  {
    id: "cold-beet-soup",
    title: "Cold Beet Soup",
    type: "travel",
    rating: 5,
    mood: "calm",
    atmosphere: { x: 34, y: 78 },
    weather: "27°C · Sun · Midday",
    notes: "Pink, cold, gentle. A perfect hot-day lunch.",
    wantToRecreate: true,
    restaurantName: "Amandus",
    city: "Vilnius",
    country: "Lithuania",
    entryDate: "2026-05-30",
    tags: ["Lithuanian", "Travel", "Light", "Summer", "Favorites"],
    photos: [{ id: "cold-beet-1", imageUrl: img("photo-1547592180-85f173990554"), alt: "A bright bowl of cold soup" }]
  },
  {
    id: "tomato-salami-pasta",
    title: "Tomato Salami Pasta",
    type: "home",
    rating: 4,
    notes: "The weeknight one. Salty edges, glossy sauce.",
    recipe: "Render salami, bloom garlic and chilli, add crushed tomato, finish pasta in the sauce with parmesan.",
    timeMinutes: 28,
    city: "London",
    country: "United Kingdom",
    entryDate: "2026-05-24",
    tags: ["Italian", "Quick", "Comfort", "Home"],
    photos: [{ id: "tomato-pasta-1", imageUrl: img("photo-1551183053-bf91a1d81141"), alt: "Tomato pasta in a shallow bowl" }]
  },
  {
    id: "taiwanese-fried-chicken",
    title: "Taiwanese Fried Chicken",
    type: "home",
    rating: 5,
    notes: "Basil crackle. Five-spice dust everywhere.",
    recipe: "Marinate chicken thigh in soy, garlic, ginger, and five spice. Coat with sweet potato starch, fry twice, and toss with fried basil.",
    timeMinutes: 55,
    city: "London",
    country: "United Kingdom",
    entryDate: "2026-05-18",
    tags: ["Taiwanese", "Comfort", "Home", "Rich", "Favorites"],
    photos: [{ id: "fried-chicken-1", imageUrl: img("photo-1562967916-eb82221dfb92"), alt: "Crispy fried chicken pieces" }]
  },
  {
    id: "mushroom-risotto",
    title: "Mushroom Risotto",
    type: "home",
    rating: 4,
    notes: "Creamy without cream. Good rainy-night food.",
    recipe: "Toast rice, deglaze with white wine, ladle in mushroom stock, finish with butter, parmesan, and thyme mushrooms.",
    timeMinutes: 42,
    city: "London",
    country: "United Kingdom",
    entryDate: "2026-05-13",
    tags: ["Italian", "Vegetarian", "Comfort", "Winter", "Home"],
    photos: [{ id: "mushroom-risotto-1", imageUrl: img("photo-1476124369491-e7addf5db371"), alt: "Mushroom risotto with herbs" }]
  },
  {
    id: "smoked-eel",
    title: "Smoked Eel",
    type: "restaurant",
    rating: 5,
    notes: "Silky, smoky, tiny and memorable.",
    restaurantName: "40 Maltby Street",
    city: "London",
    country: "United Kingdom",
    entryDate: "2026-05-08",
    tags: ["Seafood", "Restaurant", "London", "Favorites"],
    photos: [{ id: "smoked-eel-1", imageUrl: img("photo-1544025162-d76694265947"), alt: "Smoked fish with bread" }]
  },
  {
    id: "sourdough-breakfast",
    title: "Sourdough Breakfast",
    type: "home",
    rating: 4,
    notes: "Jam, salted butter, strong coffee.",
    city: "London",
    country: "United Kingdom",
    entryDate: "2026-04-29",
    tags: ["Home", "Quick", "Light", "Breakfast"],
    photos: [{ id: "sourdough-breakfast-1", imageUrl: img("photo-1541519227354-08fa5d50c44d"), alt: "Toast and breakfast on a table" }]
  },
  {
    id: "sesame-noodles",
    title: "Sesame Noodles",
    type: "recipe",
    rating: 5,
    notes: "Cold, nutty, almost too easy.",
    recipe: "Whisk sesame paste, soy, black vinegar, chilli oil, sugar, and noodle water. Toss with cold noodles and cucumber.",
    timeMinutes: 16,
    city: "London",
    country: "United Kingdom",
    entryDate: "2026-04-22",
    tags: ["Taiwanese", "Quick", "Vegetarian", "Summer", "Home", "Favorites"],
    photos: [{ id: "sesame-noodles-1", imageUrl: img("photo-1612929633738-8fe44f7ec841"), alt: "Sesame noodles with cucumber" }]
  },
  {
    id: "dumpling-sunday",
    title: "Dumpling Sunday",
    type: "home",
    rating: 5,
    notes: "A quiet afternoon of folding, then steam on the windows.",
    recipe: "Pork, cabbage, ginger, white pepper, and sesame oil. Pan-fry until the bottoms are crisp.",
    timeMinutes: 75,
    city: "London",
    country: "United Kingdom",
    entryDate: "2026-04-14",
    tags: ["Taiwanese", "Comfort", "Home", "Favorites"],
    photos: [{ id: "dumpling-sunday-1", imageUrl: img("photo-1496116218417-1a781b1c416c"), alt: "Dumplings in a bowl" }]
  },
  {
    id: "grilled-mackerel",
    title: "Grilled Mackerel",
    type: "home",
    rating: 4,
    notes: "Charred skin, cucumber, rice. Very clean.",
    recipe: "Salt mackerel for 20 minutes, grill hot, serve with rice, grated ginger, cucumber, and lemon.",
    timeMinutes: 30,
    city: "London",
    country: "United Kingdom",
    entryDate: "2026-04-04",
    tags: ["Seafood", "Quick", "Light", "Home"],
    photos: [{ id: "grilled-mackerel-1", imageUrl: img("photo-1519708227418-c8fd9a32b7a2"), alt: "Grilled fish with lemon" }]
  },
  {
    id: "ricotta-ravioli",
    title: "Ricotta Ravioli",
    type: "restaurant",
    rating: 4,
    notes: "Soft pasta, lemon butter, a tiny luxury.",
    wantToRecreate: true,
    restaurantName: "Padella",
    city: "London",
    country: "United Kingdom",
    entryDate: "2026-03-28",
    tags: ["Italian", "Restaurant", "Comfort", "London"],
    photos: [{ id: "ricotta-ravioli-1", imageUrl: img("photo-1473093295043-cdd812d0e601"), alt: "Fresh pasta with cheese" }]
  },
  {
    id: "taiwanese-breakfast-roll",
    title: "Taiwanese Breakfast Roll",
    type: "home",
    rating: 5,
    notes: "Egg, scallions, crisp edges, eaten standing up.",
    recipe: "Pan-fry scallion pancake, add egg, cheese if wanted, and roll with soy paste.",
    timeMinutes: 12,
    city: "London",
    country: "United Kingdom",
    entryDate: "2026-03-20",
    tags: ["Taiwanese", "Quick", "Breakfast", "Home"],
    photos: [{ id: "breakfast-roll-1", imageUrl: img("photo-1512058564366-18510be2db19"), alt: "Taiwanese-style egg roll breakfast" }]
  },
  {
    id: "vilnius-cardamom-bun",
    title: "Cardamom Bun",
    type: "travel",
    rating: 4,
    notes: "Sticky fingers, cold hands, good coffee.",
    wantToRecreate: true,
    restaurantName: "Taste Map",
    city: "Vilnius",
    country: "Lithuania",
    entryDate: "2026-03-12",
    tags: ["Travel", "Vilnius", "Cafe", "Quick"],
    photos: [{ id: "cardamom-bun-1", imageUrl: img("photo-1509440159596-0249088772ff"), alt: "A pastry and coffee" }]
  },
  {
    id: "summer-tomatoes",
    title: "Summer Tomatoes",
    type: "home",
    rating: 5,
    notes: "Tomatoes, salt, olive oil. Nothing else needed.",
    city: "London",
    country: "United Kingdom",
    entryDate: "2026-02-25",
    tags: ["Vegetarian", "Light", "Summer", "Home", "Favorites"],
    photos: [{ id: "summer-tomatoes-1", imageUrl: img("photo-1566385101042-1a0aa0c1268c"), alt: "Sliced tomatoes on a plate" }]
  },
  {
    id: "roast-duck-rice",
    title: "Roast Duck Rice",
    type: "restaurant",
    rating: 4,
    notes: "Glossy skin, ginger-scallion sauce, very fast joy.",
    restaurantName: "Four Seasons",
    city: "London",
    country: "United Kingdom",
    entryDate: "2026-02-10",
    tags: ["Restaurant", "London", "Comfort", "Quick", "Rich"],
    photos: [{ id: "roast-duck-rice-1", imageUrl: img("photo-1546833999-b9f581a1996d"), alt: "Roast duck and rice" }]
  },
  {
    id: "clams-with-basil",
    title: "Clams with Basil",
    type: "home",
    rating: 5,
    notes: "A little wok smoke, a lot of basil.",
    recipe: "Steam clams with ginger, garlic, rice wine, soy, chilli, and basil. Serve immediately.",
    timeMinutes: 22,
    city: "London",
    country: "United Kingdom",
    entryDate: "2026-01-27",
    tags: ["Taiwanese", "Seafood", "Quick", "Home", "Favorites"],
    photos: [{ id: "clams-basil-1", imageUrl: img("photo-1565680018434-b513d5e5fd47"), alt: "Clams with herbs" }]
  },
  {
    id: "pumpkin-soup",
    title: "Pumpkin Soup",
    type: "home",
    rating: 3,
    notes: "Soft and sweet. Needed chilli oil.",
    recipe: "Roast pumpkin with onion, blend with stock, finish with yoghurt and seeds.",
    timeMinutes: 45,
    city: "London",
    country: "United Kingdom",
    entryDate: "2026-01-13",
    tags: ["Vegetarian", "Light", "Winter", "Home"],
    photos: [{ id: "pumpkin-soup-1", imageUrl: img("photo-1476718406336-bb5a9690ee2a"), alt: "Pumpkin soup in a bowl" }]
  },
  {
    id: "brown-butter-gnocchi",
    title: "Brown Butter Gnocchi",
    type: "home",
    rating: 4,
    notes: "Sage, brown butter, soft pillows.",
    recipe: "Pan-fry gnocchi in brown butter with sage. Add lemon, parmesan, and black pepper.",
    timeMinutes: 24,
    city: "London",
    country: "United Kingdom",
    entryDate: "2025-12-21",
    tags: ["Italian", "Vegetarian", "Comfort", "Rich", "Home"],
    photos: [{ id: "brown-butter-gnocchi-1", imageUrl: img("photo-1589302168068-964664d93dc0"), alt: "Gnocchi with butter sauce" }]
  },
  {
    id: "oyster-night",
    title: "Oyster Night",
    type: "restaurant",
    rating: 5,
    notes: "Cold shells, hot chips, small celebration.",
    restaurantName: "The Quality Chop House",
    city: "London",
    country: "United Kingdom",
    entryDate: "2025-12-08",
    tags: ["Seafood", "Restaurant", "London", "Light", "Favorites"],
    photos: [{ id: "oyster-night-1", imageUrl: img("photo-1604176354204-9268737828e4"), alt: "Oysters on ice" }]
  },
  {
    id: "kibinai",
    title: "Kibinai",
    type: "travel",
    rating: 4,
    notes: "Warm pastry after the lake walk.",
    restaurantName: "Trakai Kybynlar",
    city: "Trakai",
    country: "Lithuania",
    entryDate: "2025-11-19",
    tags: ["Lithuanian", "Travel", "Comfort", "Quick"],
    photos: [{ id: "kibinai-1", imageUrl: img("photo-1509722747041-616f39b57569"), alt: "Golden pastries on a table" }]
  },
  {
    id: "mapo-tofu",
    title: "Mapo Tofu",
    type: "home",
    rating: 5,
    notes: "Numbing, red, very rice-hungry.",
    recipe: "Fry doubanjiang, garlic, ginger, pork, and tofu. Finish with chilli oil, scallions, and toasted Sichuan pepper.",
    timeMinutes: 26,
    city: "London",
    country: "United Kingdom",
    entryDate: "2025-11-07",
    tags: ["Comfort", "Rich", "Quick", "Home", "Favorites"],
    photos: [{ id: "mapo-tofu-1", imageUrl: img("photo-1582878826629-29b7ad1cdc43"), alt: "Spicy tofu in a bowl" }]
  },
  {
    id: "lemony-beans",
    title: "Lemony Beans",
    type: "home",
    rating: 4,
    notes: "Olive oil, herbs, enough lemon to wake it up.",
    recipe: "Simmer white beans with garlic, bay, and stock. Finish with lemon, parsley, and olive oil.",
    timeMinutes: 32,
    city: "London",
    country: "United Kingdom",
    entryDate: "2025-10-18",
    tags: ["Vegetarian", "Light", "Quick", "Home"],
    photos: [{ id: "lemony-beans-1", imageUrl: img("photo-1543339308-43e59d6b73a6"), alt: "White beans with herbs" }]
  }
];

export const allTags = Array.from(new Set(seedEntries.flatMap((entry) => entry.tags))).sort();
