// Sample seed data so a fresh archive is never empty.
import type {
  BodyProfile,
  ClothingItem,
  OutfitLog,
  SimilarProfile,
  UserFeeling,
} from "@/types";
import { store, uid } from "./storage";

const feel = (f: Partial<UserFeeling>): UserFeeling => ({
  comfort: 5,
  confidence: 5,
  warmth: 5,
  formality: 5,
  protection: 5,
  authenticity: 5,
  ...f,
});

const seedBody: BodyProfile = {
  id: uid(),
  heightCm: 168,
  shoulderCm: 40,
  chestCm: 88,
  waistCm: 72,
  hipsCm: 94,
  inseamCm: 76,
  torsoCm: 47,
  legCm: 79,
  bodyType: "rectangle",
  fitPreference: "relaxed",
  notes: ["long torso", "narrow shoulder", "gets cold easily"],
  updatedAt: new Date().toISOString(),
};

const seedItems: ClothingItem[] = [
  {
    id: "seed-tee",
    name: "Washed black tee",
    category: "Tops",
    colour: "Black",
    material: "Cotton",
    season: "All-year",
    brand: "—",
    purchaseDate: "2023-04-10",
    notes: "Softened from years of washing.",
    frequencyWorn: 41,
    feeling: feel({ comfort: 9, authenticity: 8, confidence: 6, formality: 2 }),
    handNote: "Felt safe and invisible. Good for long walks and overthinking.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed-jeans",
    name: "Wide raw denim",
    category: "Bottoms",
    colour: "Indigo",
    material: "Denim",
    season: "All-year",
    brand: "—",
    purchaseDate: "2022-11-01",
    notes: "Stiff at first, moves with me now.",
    frequencyWorn: 33,
    feeling: feel({ comfort: 7, confidence: 8, protection: 7, formality: 4 }),
    handNote: "These hold me up on the days I can't.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed-coat",
    name: "Grey wool overcoat",
    category: "Outerwear",
    colour: "Grey",
    material: "Wool",
    season: "Winter",
    brand: "—",
    purchaseDate: "2021-12-20",
    notes: "Heavy in a reassuring way.",
    frequencyWorn: 18,
    feeling: feel({ warmth: 9, protection: 9, confidence: 7, formality: 6 }),
    handNote: "A room I can carry with me.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed-boots",
    name: "Black leather boots",
    category: "Shoes",
    colour: "Black",
    material: "Leather",
    season: "Autumn",
    brand: "—",
    purchaseDate: "2023-09-15",
    notes: "Finally broken in.",
    frequencyWorn: 27,
    feeling: feel({ confidence: 8, protection: 8, formality: 6, comfort: 6 }),
    handNote: "I walk differently in these.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed-scarf",
    name: "Oversized linen scarf",
    category: "Accessories",
    colour: "Oat",
    material: "Linen",
    season: "Spring",
    brand: "—",
    purchaseDate: "2024-03-02",
    notes: "Doubles as a small blanket.",
    frequencyWorn: 12,
    feeling: feel({ comfort: 8, authenticity: 7, warmth: 6, formality: 3 }),
    handNote: "Something to hide a little inside of.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed-knit",
    name: "Ribbed cardigan",
    category: "Tops",
    colour: "Cream",
    material: "Wool blend",
    season: "Autumn",
    brand: "—",
    purchaseDate: "2023-10-08",
    notes: "Pockets deep enough for cold hands.",
    frequencyWorn: 22,
    feeling: feel({ comfort: 9, warmth: 8, authenticity: 7, formality: 4 }),
    handNote: "The closest thing I own to a hug.",
    createdAt: new Date().toISOString(),
  },
];

const seedLogs: OutfitLog[] = [
  {
    id: uid(),
    date: "2026-06-20",
    weather: "Warm, overcast",
    location: "Home → studio",
    occasion: "A quiet working day",
    itemIds: ["seed-tee", "seed-jeans", "seed-boots"],
    mood: "calm",
    comfortScore: 9,
    confidenceScore: 7,
    authenticityScore: 9,
    note: "Felt confident and calm today. Didn't think about clothes once — which is the point.",
    createdAt: new Date().toISOString(),
  },
  {
    id: uid(),
    date: "2026-05-30",
    weather: "Cold wind",
    location: "Across town",
    occasion: "Seeing people I was nervous about",
    itemIds: ["seed-knit", "seed-jeans", "seed-coat", "seed-boots"],
    mood: "protected",
    comfortScore: 8,
    confidenceScore: 8,
    authenticityScore: 7,
    note: "Layered up like armour. It worked.",
    createdAt: new Date().toISOString(),
  },
];

/** Fictional cards for "People Like Me". No real users, no sharing. */
export const SIMILAR_PROFILES: SimilarProfile[] = [
  {
    id: "p1",
    name: "Archivist in Lisbon",
    heightRange: "165–170 cm",
    shoulderRange: "38–41 cm",
    bodyType: "rectangle",
    styleKeywords: ["soft tailoring", "muted", "layered"],
    climate: "mild coastal",
    outfitPhotos: [],
  },
  {
    id: "p2",
    name: "Bookbinder, Kyoto",
    heightRange: "166–169 cm",
    shoulderRange: "39–40 cm",
    bodyType: "rectangle",
    styleKeywords: ["workwear", "indigo", "utilitarian"],
    climate: "four seasons",
    outfitPhotos: [],
  },
  {
    id: "p3",
    name: "Set designer, Berlin",
    heightRange: "167–171 cm",
    shoulderRange: "40–42 cm",
    bodyType: "triangle",
    styleKeywords: ["monochrome", "oversized", "structured"],
    climate: "cold continental",
    outfitPhotos: [],
  },
  {
    id: "p4",
    name: "Gardener, Devon",
    heightRange: "164–168 cm",
    shoulderRange: "38–40 cm",
    bodyType: "hourglass",
    styleKeywords: ["earth tones", "natural fibres", "relaxed"],
    climate: "wet temperate",
    outfitPhotos: [],
  },
];

export function seedIfEmpty(): void {
  if (store.isSeeded()) return;
  if (!store.getBody()) store.setBody(seedBody);
  if (!store.getItems().length) store.setItems(seedItems);
  if (!store.getLogs().length) store.setLogs(seedLogs);
  store.markSeeded();
}
